### ISSUE TITLE
Add support for API documentation

### ISSUE THREAD

**Issue by sbrink** [Krzysztof-Cieslak/vscode-elm#1]
We should add support for the api documentation.

There's documentation online, e.g. http://package.elm-lang.org/packages/elm-lang/core/3.0.0/Char

We could take a look at the source code from elm-lang.org how it's done.

**Comment by csmith111** [comment]
Support for API documentation would be great!

Not sure if you have seen this, but there is a [but there is a Hoogle like search](http://klaftertief.github.io/package.elm-lang.org/) as well that would be cool to have in a REPL.. What do you think?

**Comment by Krzysztof-Cieslak** [comment]
https://github.com/Krzysztof-Cieslak/vscode-elm/pull/109 - adds the command that opens browser for given package / version. I think that's the best what we can have right now
