### ISSUE TITLE
Error and warning squiggles from different files showing up in wrong file

### ISSUE THREAD

**Issue by radix** [Krzysztof-Cieslak/vscode-elm#101]
I regularly see error-squiggles in files when the error is actually in a different file that I currently have open. Attached an image as an example. I'm looking at View.elm but the referenced warning is from Model.elm.

![vscode-elm bug](https://cloud.githubusercontent.com/assets/227068/22856774/0c41bb92-f05e-11e6-8aa4-e07d9e00f0f6.png)

**Comment by doxxx** [comment]
I'm seeing the same thing. It looks like it happens when I have modified multiple files and use File->Save All. If one of the file has errors, those errors are displayed in all the other saved files as well. I do not have Auto Save turned on.

**Comment by littleStudent** [comment]
I have the same results. But i do not use `Save All`.

**Comment by Krzysztof-Cieslak** [comment]
Can anyone provide us any reasonable way of reproducing the problem? ;-)

**Comment by doxxx** [comment]
I am unable to reproduce the problem with the latest VS Code (1.12.1) and elm extension (0.10.0).
