### ISSUE TITLE
Possiblity to set elm-format as we can for elm-make?

### ISSUE THREAD

**Issue by chadrien** [Krzysztof-Cieslak/vscode-elm#107]
Hey,

First of all thanks for the awesome vscode plugin!

Do you think it would be possible to add an `elm.formatCommand` option just like `elm.makeCommand`? i don't like installing npm packages globally, so `elm-format` is a dev dependency for my project, hence not in `$PATH`, and this option would allow me to still be able to use this nice feature :)

**Comment by Krzysztof-Cieslak** [comment]
Sounds reasonable for me.

**Comment by miniBill** [comment]
Isn't this solved?

**Comment by chadrien** [comment]
Yes it is!
