### ISSUE TITLE
Alt+Shift+7 conflicts with entering `\` key on German keyboard on Mac

### ISSUE THREAD

**Issue by sma** [Krzysztof-Cieslak/vscode-elm#110]
Please consider to remap `Elm: REPL Send line` to some other key combination because once installed, the binding makes it impossible to enter `\` anywhere. The obvious workaround is of course to remove that binding but it would be nice if that wouldn't be needed.

**Comment by Krzysztof-Cieslak** [comment]
You can override any keyboard shortcut in VSCode using `keybindings.json` (https://code.visualstudio.com/docs/getstarted/keybindings#_advanced-customization).

While I understand it's annoying (sorry for that :-( ) there is no way we can choose default shortcuts that will work on any language and any keyboard layout.
