### ISSUE TITLE
The future of project

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [Krzysztof-Cieslak/vscode-elm#113]
I think we should change few things in terms of project structure / maintainers/ deployment process.

Right now, we have theoretically 3 maintainers:
* @sbrink - who owns repository, registered plugin on VSCode marketplace, and is only one able to deploy new version to marketplace
* @rojepp 
* and me

Right now, it looks like that I'm the only one who still is actively looking at this repository - granted, I don't do too much myself but at least I'm trying to merge PRs etc. I also can't even deploy new version to the marketplace (and the version that is in the marketplace is rather outdated) what stops me from any serious work on this project (why even bother if it won't be released?) 

I'd be willing to step up and do more for the project but to do so I need more control over the process. 

My suggestion would be:
1. Transfer the repo to me (still keeping write access for all maintainers)
2. Transfer the ownership of plugin in marketplace to me

**Comment by rojepp** [comment]
I'm fine with this. You're right, I haven't been watching this repo, mainly because I haven't used Elm that much.. :-/

**Comment by sbrink** [comment]
I'm fine with it, too. 

The repo part is easy. Not sure how to transfer the ownership of the plugin.

**Comment by sbrink** [comment]
* The repo transfer is pending
* You're invited to the team on the marketplace
* I'll transfer marketplace publisher ownership after change of the publisher name

What publisher name do you prefer for the marketplace? 

In hindsight "sbrink" was a bad publisher name. I can change the name but I'm not sure what happens to the current plugin users. If all users are lost, maybe it's a good idea to use a more generic name like elm-users, elm-plugin, elm-dev, whatever :)

Ideas?

**Comment by Krzysztof-Cieslak** [comment]
I believe that you also need to go to https://marketplace.visualstudio.com/manage/publishers and add me as an owner over there

**Comment by Krzysztof-Cieslak** [comment]
Also, as I understand this won't transfer plugin as such. I'll ask guys from Code team if it's possible at all, or we will be forced to republish plugin as new one

**Comment by sbrink** [comment]
You're added as an owner for the marketplace as well :)

**Comment by Krzysztof-Cieslak** [comment]
OK, so I've confirmed with VSCode Team that there is no way to transfer plugin to new publisher.

We can 
1. Unpublish plugin from old publisher and publish it again with new publisher - this way we will lose all stats / reviews etc, and it would require all users to reinstall plugin
Or
2. Change display name of old publisher - ID under the hood will stay the same (`sbrink`) but we will have nice display name in the marketplace / VSCode extension explorer.

Opinions?

**Comment by sbrink** [comment]
We should unpublish the plugin and give the new publisher a general name.

Before that we republish it, we should publish a version with notice of the new name.

Any objections?

**Comment by rojepp** [comment]
Maybe just put it under the Ionide brand?

**Comment by Krzysztof-Cieslak** [comment]
Ionide is reasonable suggestion.... I need to think about it a bit. For now, I'll publish new plugin version on old publisher

**Comment by Krzysztof-Cieslak** [comment]
@sbrink, Have you changed anything recently? Looks like I don't have access to plugin on the marketplace.

**Comment by sbrink** [comment]
I haven't.

To be honest, I find the whole marketplace settings confusing.

I just tried to remove myself from the project but couldn't find the settings.

**Comment by sbrink** [comment]
Seems a Microsoft issue. I can't do it myself. 
Can you remove me from the publisher and elm project?

Publisher: https://marketplace.visualstudio.com/manage/publishers/sbrink
<img width="589" alt="screen shot 2017-08-10 at 10 45 38" src="https://user-images.githubusercontent.com/55469/29162348-74347a6c-7db9-11e7-9a07-3b330edebc53.png">

Elm-lang project: https://elm-lang.visualstudio.com/_user

**Comment by Krzysztof-Cieslak** [comment]
I don't have `Edit publisher....` button in the drop down. 

Also, something is clearly wrong on MSFT side because I don't see `Sasha Brink` as an publisher... but it seems that when I follow direct link I have access to it. I'll try to figure it out.

**Comment by Krzysztof-Cieslak** [comment]
Correction: I do see publisher when I follow direct link but when I've tried to upload new version it failed with following error:
![image](https://user-images.githubusercontent.com/5427083/29166083-57734c30-7dc5-11e7-95d3-720b290b172c.png)

**Comment by sbrink** [comment]
Then sth. is wrong. We're both owners. There are no special permission settings.

<img width="648" alt="screen shot 2017-08-10 at 12 17 37" src="https://user-images.githubusercontent.com/55469/29166254-ef89bb44-7dc5-11e7-9958-b70d74ee0799.png">

Can you remove me in the role settings?

**Comment by Krzysztof-Cieslak** [comment]
I don't have access to this panel - it's on the window that's opened by `Edit publisher....` and I don't have this button on the dropdown when I'm on `sbrink` publisher page.

Can you try removing me and adding again in the roles setting?

**Comment by sbrink** [comment]
Done. Does it work?

**Comment by Krzysztof-Cieslak** [comment]
Nope, still same behavior.

I'll try to get in touch with someone from MSFT, maybe they'll be able to help.

**Comment by sbrink** [comment]
Okay, just remove me if you get access :-)

**Comment by Krzysztof-Cieslak** [comment]
After few days of email exchange with folks from MSFT I now have access to the publisher again. 

@sbrink: I've removed you from owners of publisher.

**Comment by sbrink** [comment]
👍
