### ISSUE TITLE
Release via CI

### ISSUE THREAD

**Issue by sbrink** [Krzysztof-Cieslak/vscode-elm#116]
@Krzysztof-Cieslak 

Until now a new release was automatically published via codeship.
Here are the old commands:

```
nvm install 5.0
npm install -g vsce
npm install
echo '{"publishers":[{"name":"publishername","pat":"..."}]}' > ~/.vsce
vsce publish
```

Just close the ticket if you don't need it

**Comment by Krzysztof-Cieslak** [comment]
Thanks for info :)
