### ISSUE TITLE
Intellisense not working anymore

### ISSUE THREAD

**Issue by miniBill** [Krzysztof-Cieslak/vscode-elm#117]
Since I've installed the latest version the Intellisense isn't working anymore.

I get no autocompletions and no hover popups for types and functions.

Errors and warnings are correctly reported.

**Comment by Krzysztof-Cieslak** [comment]
Latest version works only for Elm 0.18, maybe you're using older version of Elm?

**Comment by cbenz** [comment]
I have the same issue and spotted this exception in VSCode debugger console:

![image](https://cloud.githubusercontent.com/assets/12686/25815648/b83d6fa2-3421-11e7-80d4-f8b4a4330b4e.png)

What's important I think is `Error: ENOENT: no such file or directory, open '/home/cbenz/Dev/myproject\elm-package.json'` and the fact that the path mixes `/` and `\`.

**Comment by Krzysztof-Cieslak** [comment]
Can you please check out `0.11.0` ?

**Comment by cbenz** [comment]
It works again!

I'm not sure whether it's related, but I see another exception though:

![image](https://cloud.githubusercontent.com/assets/12686/25849387/8f75c8b0-34be-11e7-8b51-24f116cf8163.png)

I didn't dive into. Feel free to create another issue if irrelevant.

And thanks for the fix!

**Comment by cbenz** [comment]
For the record this was fixed by de835bd591f10c96157f4d5ffa204a88712b0203
