### ISSUE TITLE
Showing documentation on hover

### ISSUE THREAD

**Issue by teesloane** [Krzysztof-Cieslak/vscode-elm#122]
Hi folks! 

I'm not sure if I've misremembering this so, this may be a null issue.

At some point I think I recall vscode-elm showing docstrings / comment documentation on hovering over a locally written function. 

![giphy](https://cloud.githubusercontent.com/assets/12987958/26322751/582fbabe-3efa-11e7-876f-a70da4362b5e.gif)

Let me know if I can provider further documentation. Thank you for all your hard work.

**Comment by andrewsdev** [comment]
I can take this once PR #135 is merged in.

I'll add a new setting "elm.includeCommentsInUserFunctions" defaulted to true to control it.  

Note that this would only be applicable to user-created functions as you say.

**Comment by teesloane** [comment]
Awesome! Thanks @andrewsdev . I appreciate your hard work.

**Comment by andrewsdev** [comment]
Please try out the latest version 0.14.1 , this feature has been added.

**Comment by teesloane** [comment]
Awesome!
