### ISSUE TITLE
Duplicate module name on autocomplete

### ISSUE THREAD

**Issue by adriantoine** [Krzysztof-Cieslak/vscode-elm#123]
Hi!

I'm having an issue when I'm using the autocomplete feature.

See the gif:

![vscode-elm](https://cloud.githubusercontent.com/assets/976570/26398672/1a57f908-4072-11e7-9eb0-8ba98cccbac9.gif)

It autocompletes to `Maybe.Maybe.andThen` instead of `Maybe.andThen`, I don't know if it's just me. 🤔 It seems I'm the only one having this issue.

Thanks!

**Comment by kraklin** [comment]
Hi, you are not the only one. I'm having the same issue. 

MacOS 10.12.5
VSCode 1.12.2
vscode-elm 0.11.2
