### ISSUE TITLE
Can't get highlighting to work on Windows 7

### ISSUE THREAD

**Issue by fjanon** [Krzysztof-Cieslak/vscode-elm#151]
I installed elm and following the install instructions here but it get this error:

// Place your settings in this file to overwrite default and user settings.
{
  "elm.makeCommand": "./node_modules/.bin/elm-make"
}

file: 'file:///c%3A/project/static/.vscode/settings.json'
severity: 'Warning'
message: 'Unknown configuration setting'
at: '3,3'
source: ''

Any idea how to fix that?

I tried also using the global install with the .exe but I don't know how to point at the elm-make.exe, when I use:

"elm.makeCommand": "elm-make"

I get the same error and no highlighting.

**Comment by hakonrossebo** [comment]
I have not tried setting this setting in Windows, but I can try it later today. Anyways - if you use the global installation of elm, you should not need to set this setting at all.

By the way - the simple elm-make command seems correct - are you editing the correct user settings file?

**Comment by fjanon** [comment]
Thanks for your offer Håkon, I ended up by reinstalling VSCode, the elm extension and restarting VSCode.

I probably didn't restart VSCode before checking Elm highlighting.

I think it would be nice to add some instructions to add the Elm extension for VSCode and to restart it.

Looking forward to use it!

Thanks again. Cheers.

**Comment by hakonrossebo** [comment]
Great that it worked out. Please create issues for any other startup issues with this extension - I think it's very important to smooth out any rough edges for new users.
