### ISSUE TITLE
add prettier for code-formatting

### ISSUE THREAD

**Issue by littleStudent** [Krzysztof-Cieslak/vscode-elm#153]
I talked with @hakonrossebo about adding [prettier](https://github.com/prettier/prettier) to the project to enforce a consistent code-style.

So my question is if this is something you want to add to the project @Krzysztof-Cieslak ?
If so, i can add a prettier setup.

edit:
I am not talking about elm-format. It is meant to keep the code-style of this repo clean and consistent.

**Comment by Guysbert** [comment]
To achieve this you can use elm-format. 
https://github.com/avh4/elm-format

**Comment by hsribei** [comment]
From: https://github.com/Krzysztof-Cieslak/vscode-elm#formatting-with-elm-format

[elm-format](https://github.com/avh4/elm-format) is supported via the editor's `Format Code` command. To format your code using `elm-format`, press `Shift+Alt+F` on Windows, `Shift+Option+F` on Mac, or `Ctrl+Shift+I` on Linux.

You can also configure `elm-format` to run on save by enabling the `elm.formatOnSave` in your settings.

```
// settings.json
{
    "elm.formatOnSave": true
}
```

**Comment by littleStudent** [comment]
sorry for the confusion...
I actually meant adding this to the project for the purpose of keeping the javascript codebase of this repo clean and formatted.

**Comment by hakonrossebo** [comment]
I support adding prettier to enforce a consistent code-style for this project. Very happy how this works in Elm. I think you can add a PR for prettier if there's no other immediate objections to this.

**Comment by littleStudent** [comment]
https://github.com/Krzysztof-Cieslak/vscode-elm/pull/156
