### ISSUE TITLE
Indentation lines continue past end of block

### ISSUE THREAD

**Issue by hsribei** [Krzysztof-Cieslak/vscode-elm#154]
Not sure if "indentation line" is the right vscode terminology, but this is what I'm seeing. Sorry if this has been reported elsewhere, didn't know how to search for it.

![vscode-elm](https://user-images.githubusercontent.com/4315/28275981-936d0766-6ae3-11e7-9aa6-34794d89626b.png)

**Comment by hakonrossebo** [comment]
This is not handled by this extension, only by vscode. Seems to happen due to how code is formatted in Elm. Not sure if this should be reported as an issue in vscode instead. Tested and verified that indent guides are correct with this formatting:

main : Program Never
main =
    App.program
        { init = (model, Cmd Msg)
        , view = view
        , update = update
        , subscriptions = subscriptions
    }

**Comment by hsribei** [comment]
Could you add the example you tested inside a code block so I can verify the formatting please? Odd that it works for you but not me.

One thing I noticed that is wrong with my example is that the number of spaces should be set to 4 in vscode, but it remains the default 2, so there is one extra indent guide. Since elm-format uses 4, maybe the extension could set it to 4 for .elm files?

Regardless, when I set spaces to 4 manually, I still get two guides shooting down past the end of the block and only stopping when a new non-empty line begins. 

I've never seen this behavior in other languages, so I thought I'd check here first. If no one else is experiencing this, I'll post it upstream. Thanks for the feedback!

**Comment by hakonrossebo** [comment]
Yes, this could be related to the 4/2 spaces setting. The example I tested was by using the snippet "mainprogram". On my machine, this creates a main function that closes the indent guides correctly.

**Comment by Krzysztof-Cieslak** [comment]
Closing as it's VSCode "issue" (or rather by-design behaviour)
