### ISSUE TITLE
Disabling code snippets

### ISSUE THREAD

**Issue by gyzerok** [Krzysztof-Cieslak/vscode-elm#155]
Hi there!

Thank you for all the work you put in this package.

Is there a way to disable code snippets? They really slowing me down because usually they work in the places I don't want them to.

**Comment by Krzysztof-Cieslak** [comment]
You can disable snippets using standard VSCode settings - `"editor.snippetSuggestions": "none"`

**Comment by gyzerok** [comment]
Is there a way to disable only code snippets from this package?

**Comment by Krzysztof-Cieslak** [comment]
Don;t think so. But you can use language specific settings to disable snippets in Elm files - https://code.visualstudio.com/docs/getstarted/settings#_language-specific-editor-settings

**Comment by gyzerok** [comment]
Ok, thank you!
