### ISSUE TITLE
Multiline type annotations

### ISSUE THREAD

**Issue by swelet** [Krzysztof-Cieslak/vscode-elm#157]
Thank you for your work! 

When writing multi line type annotations, the second line is not given the same formatting as the first.

<img width="509" alt="screen shot 2017-08-17 at 11 24 00" src="https://user-images.githubusercontent.com/5476077/29405623-b17b55b4-833e-11e7-98ff-315570f3fd78.png">

I'd give it a stab myself, but I don't know the first thing about vs code extensions!

**Comment by hakonrossebo** [comment]
Not sure how this works:

The syntax file used is located here:
https://github.com/Krzysztof-Cieslak/vscode-elm/blob/master/syntaxes/elm.json

Originally from this:
https://github.com/elm-community/Elm.tmLanguage/blob/master/Syntaxes/Elm.tmLanguage

It seems to work fine in Sublime Text, so I guess we could verify any differences and PR's to this file to resolve this issue.

**Comment by hakonrossebo** [comment]
Found some documentation here: 
https://www.apeth.com/nonblog/stories/textmatebundle.html
and
https://manual.macromates.com/en/language_grammars

Also seems to be similar to the Atom plugin - https://github.com/edubkendo/atom-elm/blob/master/grammars/elm.cson

I tried to verify differences in "type-signature", but could not find any.

**Comment by swelet** [comment]
Here is a better shot of the "problem"

<img width="481" alt="screen shot 2018-04-26 at 10 30 57" src="https://user-images.githubusercontent.com/5476077/39294796-f096c7a0-493c-11e8-8559-46ee3d44a6e1.png">
