### ISSUE TITLE
Cannot execute elm-format

### ISSUE THREAD

**Issue by foxbunny** [Krzysztof-Cieslak/vscode-elm#166]
I have installed elm-format using `npm` like so:

```
npm i -g elm-format@exp
```

The `elm-format` command is in the path, and I can execute it in the command line from any location.

When I run the `ELM: Format` command, I get the following error:

>Unable to execute elm-format. Please make sure you have elm-format on your PATH

Developer console shows:

```
spawn elm-format ENOENT: Error: spawn elm-format ENOENT
	at exports._errnoException (util.js:1050:11)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:193:32)
	at onErrorNT (internal/child_process.js:367:16)
	at _combinedTickCallback (internal/process/next_tick.js:80:11)
	at process._tickCallback (internal/process/next_tick.js:104:9)
e.onUnexpectedError @ shell.ts:419
(anonymous) @ shell.ts:379
e.onUnexpectedError @ errors.ts:119
o @ errors.ts:138
e.$onUnexpectedError @ mainThreadErrors.ts:26
e.invoke @ abstractThreadService.ts:41
e._invokeHandler @ rpcProtocol.ts:109
e._receiveOneMessage @ rpcProtocol.ts:96
(anonymous) @ rpcProtocol.ts:32
(anonymous) @ rpcProtocol.ts:157
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ ipc.net.ts:82
emitOne @ events.js:96
emit @ events.js:191
readableAddChunk @ _stream_readable.js:178
Readable.push @ _stream_readable.js:136
onread @ net.js:560
messageService.ts:125 Unable to execute elm-format. Please make sure you have elm-format on your PATH
e.doShow @ messageService.ts:125
e.show @ messageService.ts:104
e.resume @ messageService.ts:63
(anonymous) @ workbench.ts:1016
e.invoke @ callbackList.ts:63
e.fire @ event.ts:123
(anonymous) @ quickOpenController.ts:518
```

EDIT:

This is on VSCode 1.16.1 on Windows 10.

**Comment by leobm** [comment]
I had the same problem. With the release version https://github.com/avh4/elm-format/releases/download/0.7.0-exp/elm-format-0.18-0.7.0-exp-win-i386.zip it works. 
I copy the elm-format.exe to my 'Elm Platform' bin Folder. This directory is set to my PATH environment variable.

**Comment by oren-l** [comment]
@foxbunny try using Alt+Shift+F (shortcut for "Format Document")
I had the same issue and it drove me nuts, just realized now that I had other extension called "elm-format" and I confused it with this extension.

As [elm-format](https://marketplace.visualstudio.com/items?itemName=abadi199.elm-format) has been removed from vscode marketplace it is no longer visible in vscode extension tab so you can't disable it from within vscode, to remove it delete `%USERPROFILE%\.vscode\extensions\abadi199.elm-format-0.1.0` folder

**Comment by foxbunny** [comment]
>  to remove it delete %USERPROFILE%\.vscode\extensions\abadi199.elm-format-0.1.0 folder

Wow. That was a simple fix indeed. :D If anyone runs into this, I also had to install the `elm-analyse` NPM package to suppress some possibly unrelated messages.
