### ISSUE TITLE
Vertical Space Compression?

### ISSUE THREAD

**Issue by kylecordes** [Krzysztof-Cieslak/vscode-elm#168]
(feature request)

Elm code formatted by elm-format uses a lot of vertical space - many blank lines, often 2 or 3 of them in a row. Many of us (like me) really like to automatically run elm-format. Elm code therefore uses up a lot of vertical space on the screen. I really enjoy this airy, spread out appearance... in some contexts.

But sometimes, I need to look at more code at the same time, to understand (or explain to someone else, without scrolling) how pieces interact. Sometimes, I want to explain some code to a group of people, and am stuck with an old, low resolution, dim projector. Sometimes I am 40+ years old, and don't read tiny text as easily as a 20-year-old.

Therefore, I'd like to see a way, at the IDE level, to do "vertical space compression": render blank lines as a more narrow strip of screen space, perhaps 50% smaller than usual. This would support the scenarios where it is helpful to see more lines of code at once, *without* changing the layout of the code, without changing elm-format, without inviting any division in the community about how code should be formatted, etc.

Is this a good idea? Is it possible to implement in a VSCode extension? Does anyone else care about this, but me?

**Comment by Krzysztof-Cieslak** [comment]
That's the feature that suggested in VSCode repo, extension API doesn't allow such UI changes.
