### ISSUE TITLE
Elm-format does nothing

### ISSUE THREAD

**Issue by Janjuks** [Krzysztof-Cieslak/vscode-elm#170]
Hi.

Formatting document doesn't seem to do anything.
I would expect that these unnecessary line breaks and spaces would be removed. At least that's how I remember it working. Coming back to Elm after a long pause and this is on fresh install. Restarted PC, but that didn't help.
![image](https://user-images.githubusercontent.com/8797504/31632322-2c77b270-b2c5-11e7-9ae4-bb2b85a0d64a.png)

Elm version: 0.18.0
Code version: 1.17.1
vscode-elm version: 0.15.1
OS: Windows 10

**Comment by boaz-chen** [comment]
Same here.

Elm version: 0.18.0
VSCode: 1.17.2
vscode-elm: 0.15.1
OS: macOS 10.13

Thanks

**Comment by lukaszgasior** [comment]
@Janjuks - it is working fine for me

VSCode - 1.17.2
VSCode-elm - 0.15.1
ELM: 0.18.0
OS: Windows 10

do you have `elm-format` installed on your computer?
locally or globally?

**Comment by Janjuks** [comment]
@lukaszgasior I don't. Do I have to? I had the impression that this package does that.

**Comment by lukaszgasior** [comment]
@Janjuks yes, you need to have `elm-format`
this plugin is just running this tool

if you have `elm-format` installed globally it should just work
if you have `elm-format` installed locally please check this link: https://github.com/Krzysztof-Cieslak/vscode-elm#elm-format---local-installation

**Comment by Janjuks** [comment]
Sorry and thanks, it works now!
