### ISSUE TITLE
Project (Local) installation does not work for VSCode 1.18?

### ISSUE THREAD

**Issue by witoldsz** [Krzysztof-Cieslak/vscode-elm#173]
I was working in VS Code few months ago and I remember I did not have troubles with local installation. Now I am back to Code and I am trying to use `elm-make` from `node_modules/.bin`:
```
"elm.makeCommand": "./node_modules/.bin/elm-make"
```
It does not work: _The 'elm-make' compiler is not available. Install Elm from http://elm-lang.org/._

VS Code 1.18 introduced multi-root workspaces. Could it be the case?

**Comment by littleStudent** [comment]
is elm-make installed at `"./node_modules/.bin/elm-make"`?

**Comment by witoldsz** [comment]
Yes, it is. The only way to make it working is to provide full, absolute path.

**Comment by Krzysztof-Cieslak** [comment]
I think it may be connected with changes in configuration API introduced with multi-root workspaces. By any chance, you have multiple workspaces open?

**Comment by witoldsz** [comment]
As of now I tried to make it all simple, so I have closed everything, then "open folder" with my elm/js project – the way I did it some time ago, when there was no multi-root project.

**Comment by boaz-chen** [comment]
See https://github.com/Microsoft/vscode/wiki/Extension-Authoring:-Adopting-Multi-Root-Workspace-APIs, and specifically the following section:

Do I need to do anything?

Here is a simple check list:

If your extension is making use of the (now deprecated) workspace.rootPath property to work on the currently opened folder, then you are affected. See the section 'Eliminating workspace.rootPath below'.

**Comment by boaz-chen** [comment]
Not sure what happened, but things started working for me all of a sudden. I did a restart just before due to an unrelated issue, but I don't think that this was it since I've also restarted when I initially encountered this issue to try and see whether that solved it, and it didn't.

So now elm-make, elm-format, etc work as expected.
