### ISSUE TITLE
Cursor jumping to EOF when `formatOnSave` is triggerd

### ISSUE THREAD

**Issue by Dtatoo** [Krzysztof-Cieslak/vscode-elm#174]
vscode version in question: 1.18.1 (1.18.1) (OS X)

When formatting are complete cursor automatically jumps to EOF.

This issue is also reported on https://github.com/Microsoft/vscode/issues/38728

Depending on how that issue is resolved it may be necessary to copy all the diffing code from vscode to this extension.

**Comment by Stijnkool** [comment]
For me it jumps to the end of the file.

**Comment by Dtatoo** [comment]
Oops sorry about that. EOF is what I am getting as well

**Comment by Dtatoo** [comment]
Seems to be a vscode problem. Closing this issue.
