### ISSUE TITLE
formatOnSave not working from VsCode

### ISSUE THREAD

**Issue by thepreacher** [Krzysztof-Cieslak/vscode-elm#175]
I'm on mac running vscode ver. 1.18.1 and have the following in my settings.json file:

    `// Format a file on save. A formatter must be available, the file must not be auto-saved, and editor   must not be shutting down.
    "editor.formatOnSave": true,

    // Runs elm-format on the file every time it is saved
    "elm.formatOnSave": true,`

Nothing happens when I modify and save a file nor when I use the keybord shortcut `Shift+Option+F`

From the command prompt and in any folder with an elm file however, I am able to type `elm-format <filename>` and it works as expected.

Strange thing is, it used to work when I had the now unpublished `elm-format` plugin installed.

**Comment by harmboschloo** [comment]
This got it working again for me.

```
{
  "editor.formatOnSave": true,
  "elm.formatOnSave": true,
  "[elm]": {
    "editor.formatOnSave": false
  }
}
```

**Comment by harmboschloo** [comment]
Note that I had this problem on windows with vscode v1.19.1.

**Comment by ikovic** [comment]
I'm working on mac too, VS Code v1.19.1, 0.15.1 version of elm extension. Code formatting is not working and the above fix does not help.

**Comment by Krzysztof-Cieslak** [comment]
From `0.16` the `"elm.formatOnSave"` setting is removed, and `editor.formatOnSave` should be used.

**Comment by rokit** [comment]
I agree with @ikovic. It also was not obvious to me that elm-format did not come with this extension. +1 for making this more explicit in the readme.
