### ISSUE TITLE
Cursor jump to last line of the file when save

### ISSUE THREAD

**Issue by kkpoon** [Krzysztof-Cieslak/vscode-elm#176]
vscode 1.18.1
elm extension 0.15.1

when save the elm file, the cursor jump to the end of the file.

**Comment by Stijnkool** [comment]
Although multiple plugins experience this issue, it won't be fixed within vscode.
It's up to the plugin authors to fix it. A high level solution is supplied in the reported issue. https://github.com/Microsoft/vscode/issues/38728

**Comment by Krzysztof-Cieslak** [comment]
Duplicate of #174

**Comment by Stijnkool** [comment]
Why is this issue closed?
This is not a bug in vscode itself.
It is a bug in the plugin as explained in https://github.com/Microsoft/vscode/issues/38728.

**Comment by allansideas** [comment]
This only happens with "editor.formatOnSave": true, when running via the "ctrl+shift+p" Format Document shortcut, it doesn't jump to the EOF.

**Comment by joshhornby** [comment]
This should be reopened, as it's a bug in this library.

**Comment by joshhornby** [comment]
Anyone have any ideas on this? According to this comment https://github.com/Microsoft/vscode/issues/38728#issuecomment-349280013 we might need to not replace the entire document but just the section that's changed. Does `elm-format` support this?
