### ISSUE TITLE
'.' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by Janjuks** [Krzysztof-Cieslak/vscode-elm#177]
Hi.

I get that this is related to Windows system variables, but I can't figure out what is wrong. Hopefully you can help me.

Whenever I save one of elm files, it throws `'.' is not recognized as an internal or external command, operable program or batch file` error.
http://prntscr.com/hhoiz7

User variables seem good to me: http://prntscr.com/hhokhi

```
    Directory: C:\Program Files (x86)\Elm Platform\0.18\bin


Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
-a----       2016-11-12     02:47       12126734 elm-make.exe                                                          
-a----       2016-11-12     02:45        9840142 elm-package.exe                                                       
-a----       2016-11-12     02:49        8451598 elm-reactor.exe                                                       
-a----       2016-11-12     02:46        6365198 elm-repl.exe                                                          
-a----       2016-11-12     02:42        4485646 elm.exe             
```

**Comment by Janjuks** [comment]
Can I get some look into this?
I have reinstalled vscode, extension, but with no success.
Actually the only thing that's working is elm-format. 
I have no syntax highlighting, no autocomplete, no error highlighting, etc.

vscode version `1.18.1`

**Comment by Krzysztof-Cieslak** [comment]
It's probably some bug similar to https://github.com/Krzysztof-Cieslak/vscode-elm/issues/93

**Comment by Janjuks** [comment]
I don't have ImageMagick installed, but of course, it could be another program.
I could try to confirm/deny that, but I don't know how to look up what calls extension is making, like @ConnyOnny provided in #93

**Comment by rayjsiu** [comment]
@Janjuks Sounds like the Elm extension cannot find the elm-make executable.
If Elm is accessible globally in your environment (From command-line, if you type `elm-make` works), in your settings/preferences for VS Code, try setting:
```json
"elm.makeCommand": "elm-make",
```

**Comment by Janjuks** [comment]
Thanks! For some reason `elm.makeCommand` was overwritten to `./node_modules/.bin/elm-make`
All good now!
