### ISSUE TITLE
backslash on macosx on a nordic keyboard does not work

### ISSUE THREAD

**Issue by ulve** [Krzysztof-Cieslak/vscode-elm#181]
pressing alt + shift + 7 should produce backslash but runs `elm.replSendLine`. It is not hard to fix but it is not that easy to figure out that the elm extensions makes it impossible to write lambdas.

**Comment by ulve** [comment]
the f# extension uses the same binding for the same thing so it is quite common I guess

**Comment by Krzysztof-Cieslak** [comment]
We have no way of defining custom bindings for custom keyboard settings in the plugin. 

You can change any key binding in VSCode as described here - https://code.visualstudio.com/docs/getstarted/keybindings

**Comment by axelo** [comment]
Maybe put this in the README section somwhere, got the same issue and could resolve it 'cause I found this report.
