### ISSUE TITLE
Cursor moving after formatOnSave

### ISSUE THREAD

**Issue by seestevecode** [Krzysztof-Cieslak/vscode-elm#182]
When using the formatOnSave option, the cursor moves to the end of the file when saving/formatting. This doesn't happen if doing a manual format with Alt-Shift-F, nor when saving with formatOnSave turned off. Would be good to have the cursor retaining position with formatOnSave too.

**Comment by joshhornby** [comment]
I am also seeing this issue.

```
Version 1.19.1
Commit 0759f77bb8d86658bc935a10a64f6182c5a1eeba
Date 2017-12-19T09:46:23.884Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by joshhornby** [comment]
For further context: https://github.com/Microsoft/vscode/issues/38728

**Comment by tbash** [comment]
I am having this same issue when saving with Cmd+S, however, I am using the [VSCodeVim](https://github.com/VSCodeVim/Vim) plugin. When using the "vim way" to save a file (`:w`), it auto-formats correctly and I do experience this. Maybe a perfect time to incorporate vim keybindings into the ol' workflow?

**Comment by rtfeldman** [comment]
Seeing the same behavior with the Vim plugin. Works fine if I save from Insert Mode, but when saving from Command Mode it moves to the end of the file.

**Comment by adam77** [comment]
^^^ so removing the `willSaveTextDocument` handler and using `editor.formatOnSave` in place of `elm.formatOnSave` seems to solve the issue; but i suspect the handler is required for something i'm unaware of?
