### ISSUE TITLE
elm-analyze running but no problem shown

### ISSUE THREAD

**Issue by albertored** [Krzysztof-Cieslak/vscode-elm#184]
I can successfully start and stop elm-analyze from vscode but I don't get any Problem/Warning in the corresponding tab. The `elm-analyze` output reports some message `Found 25 message(s)` and also if I navigate to http://localhost:3379 I correctly see the warnings

elm-analyze version: `0.13.3`

Vscode version
```
Version 1.20.0-insider
Commit ed4c237467bfe7c37b173da782cb65e333484a13
Date 2018-01-26T06:15:49.284Z
Shell 1.7.9
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64
```

**Comment by jhf** [comment]
I have the same issue; `elm-analyse` is running and reporting `Found X message(s)` and navigation directly to elm-analyse on http://localhost:3379 shows the messages/warnings, however, there are is no output in the Problems (`Ctrl+Shift+M`) window and there are no green squiggles in for instance `App.elm` when I open the file.

I'm running vscode `1.22.2`,  Elm extension `0.16.0` and elm-analyse `0.14.0`.
I do however notice that there is a apparently permanent message of
`elm-analyse websocket waiting 3 seconds to ensure server has started...`

**Comment by Krzysztof-Cieslak** [comment]
@stil4m @hakonrossebo any idea? 

I can reproduce an issue - `elm-analse` starting correctly, and running, errors reported in web interface, no errors in editor.

**Comment by stil4m** [comment]
The structure of the messages which elm-analyse producers changed in 0.13. using a version prior to this is the easy fix for the problem.

Bumping the plugin to support the data which elm-analyse producers since 0.13 will take some effort. Supporting all newer and onder versions would be tedious.

Im working on functionality that will remove the compatibility issues between a plugin and elm-analyse. That is currently focussing on Atom, but van easily be adapted to VScode. I'll check in when I reach that stage.

**Comment by Krzysztof-Cieslak** [comment]
@stil4m Thanks a lot for info :)

**Comment by Krzysztof-Cieslak** [comment]
#206 updated integration to elm-analyse `0.14.2`

**Comment by Rolograaf** [comment]
Error: `There is no elm-package.json file in this directory. elm-analyse will only work in directories where such a file is located.`

But there is a .19 `elm.json` file?

**Comment by stil4m** [comment]
`elm-analyse` was updated to version `0.16.0` (and `.1` a few days after). That version will support Elm 0.19 code.

**Comment by Maxim-Filimonov** [comment]
@stil4m the issue came back with `elm-analyse 0.16.1`. 
It runs and reports but the problems don't appear in the problems panel.
