### ISSUE TITLE
Elm code syntax highlighting in markdown source

### ISSUE THREAD

**Issue by kachkaev** [Krzysztof-Cieslak/vscode-elm#185]
I'm new to both elm and vscode, so sorry in advance if I'm opening this issue in a wrong repo.

I've installed `vscode-elm` and am already enjoying code formatting and linting! The extension is truly great!

What I've noticed though is that when I have a markdown file with the elm code blocks, syntax is not highlighted:

![screen shot 2018-02-09 at 16 53 20](https://user-images.githubusercontent.com/608862/36039230-cdac4256-0db9-11e8-8f93-279f648b8e9e.png)

Here's how the same text looks in Atom:

![screen shot 2018-02-09 at 16 53 11](https://user-images.githubusercontent.com/608862/36039260-e1235252-0db9-11e8-8eb0-f73e2fa0df8f.png)

I searched through the main vscode repo and found a couple of discussions with a reference to
[vscode-fenced-code-block-grammar-injection-example](https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example). It is suggested that the support for a new language in markdown blocks should be added by the developers of the language extension. I guess it's not a hard thing to do with some vscode experience, but as a newbie I'm not sure that that this is the right direction.

Who could help with this please?

**Comment by Krzysztof-Cieslak** [comment]
Hey, 

Thanks for pointing out this, I didn't even know that there is such extension point in VSCode! :D

As far as I understand the sample, adding this should be fairly simple all we'd need to do is adding configuration block to our `package.json` similar to: https://github.com/mjbvz/vscode-fenced-code-block-grammar-injection-example/blob/master/package.json#L21-L31

PRs are welcomed :)
