### ISSUE TITLE
Codelens support - function references

### ISSUE THREAD

**Issue by opvasger** [Krzysztof-Cieslak/vscode-elm#189]
Hello

First I'd like to thank you for this project - this extension provides an awesome experience with elm and vscode! 👍

I'm pondering writing an extension for vscode that uses the codelens extension-api to add function stats on top of function-definitions - initially to show at a glance how many references any function has throughout it's project.

Would this kind of functionality be at home in this extension or should I approach it as a separate extension?

**Comment by Krzysztof-Cieslak** [comment]
I'd be happy to include such feature here in this extension :)

**Comment by opvasger** [comment]
alright - Is there any of your current modules that could help me search files for refs and defs for functions and keep these numbers up to date?

**Comment by r1sc** [comment]
While you're at it, add function signatures (type information) to codelens as well. Ionide for F# does this and it's nice not having to type that definition just to remember it.

**Comment by opvasger** [comment]
Got into it, but [found discussions about implementing a language-server for Elm](https://github.com/Krzysztof-Cieslak/vscode-elm/issues/137), which would be much better than my half-assed implementation - so decided to do other stuff. Sorry :)
