### ISSUE TITLE
Continuous freezing

### ISSUE THREAD

**Issue by chrisolsen** [Krzysztof-Cieslak/vscode-elm#190]
I can't type more than a few characters before any keyboard entry halts for about 5 sec.

Windows 7
vscode: 1.20.1
version: 0.16

**Update**
The issue only exists when using the vscodevim extension

**Update 2**
Using the amVim extension also results in the exact same issue.

**Solved**
Turns out I didn't change the `elm-package.json` `src-directories` value from the default, but the fact that the error message appears linked to the `src/Main.elm` file doesn't lead me to think that the elm compiler is looking in the wrong directory.

**Comment by hakonrossebo** [comment]
I've also experienced this with VSCodeVim. If I understand correctly - were you able to solve this by changing any source directories?

**Comment by chrisolsen** [comment]
Yes, when the `src-directories` attribute was set everything then worked as expected.
