### ISSUE TITLE
Elm format works when used manually, but not on save - Possible issue on Windows?

### ISSUE THREAD

**Issue by hakonrossebo** [Krzysztof-Cieslak/vscode-elm#191]
This happens on my windows machine, but not on Linux. The same issue has also been reported here - https://discourse.elm-lang.org/t/fyi-for-anyone-with-vscode-who-updated-to-1-20-1/695

When debugging, this seems to work fine in stdout and in text replace, but somehow it does not show in the editor.

**Comment by adam77** [comment]
Do you have auto-save enabled?
Format-on-save does not work when auto-save is enabled. This a VSCode limitation.

**Comment by MartinKavik** [comment]
@hakonrossebo See https://github.com/Microsoft/vscode/issues/41194#issuecomment-364203142 + other comments in that thread

**Comment by hakonrossebo** [comment]
@adam77 - Thanks - no I don't have auto-save enabled. @MartinKavik - yes, this seems to be related. Verified that this format on save actually works on my Windows desktop machine - the "Running Save Participants" shows very briefly. On my Windows laptop format on save fails and the same status message is visible probably longer than 750ms. The laptop is a X1 Carbon 16GB 2017 model. On the same laptop, running Ubuntu 16.04, saving is fast and format on save works fine.

**Comment by hakonrossebo** [comment]
I just verified the new formatOnSave timeout override that got merged into VSCode insider. Seems to work ok. Use:

"editor.formatOnSaveTimeout": 1500

I'm not sure if this is an acceptable solution, as my experience is that most Windows systems needs this setting for format on save to work?

**Comment by Krzysztof-Cieslak** [comment]
It looks like setting `"editor.formatOnSaveTimeout"` is good suggested way forward for this feature.
