### ISSUE TITLE
"The 'elm-make' compiler is not availabe. Install Elm from http://elm-lang.org/"

### ISSUE THREAD

**Issue by rcilio** [Krzysztof-Cieslak/vscode-elm#193]
I've recently installed Elm via npm on a Mac running 10.11.6. I've also included elm-format. VS Code is my preferred editor, but whenever I save any .elm file I get the following warning"
"The 'elm-make' compiler is not availabe. Install Elm from http://elm-lang.org/". The elm-make compiler is, in fact, available and I can run it from the terminal with no problem. Can anyone point me in the right direction as to how I can stop these warnings? I noticed there was a similar issue for Windows operating system in 2016. Anything for Macs? The issue only seems to occur with VS Code, not Sublime Text 3 or other editors I've tried. Many thanks!

**Comment by hakonrossebo** [comment]
Do you still have this issue? Is elm installed globally in npm?

**Comment by alexandru-calinoiu** [comment]
I have it, and yes elm is installed globally, maybe it has something to do with `nvm`

**Comment by fhdhsni** [comment]
Had the same issue on Linux. Although `elm-make` was in my `$PATH`, I had to give `elm.makeCommand` the absolute path to make it work.

**Comment by Krzysztof-Cieslak** [comment]
I think this is know problem of Code (and Atom, I believe)  not having access to `PATH` when started from graphical interface on Mac (and Linux). Workarounds for that are: 
1. Starting Code from terminal 
2. Setting `elm.makeCommand`

**Comment by rofrol** [comment]
I had `$PATH` wrongly set in new vscode 1.23.0. To fix this, set in settings (for osx):

```
    "terminal.integrated.shellArgs.osx": [
      "-i"
    ],
```

By default it is `-l`.

Starting vscode from terminal sets `$PATH` correclty.

Introspection: `vscode > Help > Toggle Developers Tools > process.env.PATH`

https://github.com/Microsoft/vscode/issues/31800#issuecomment-327149392
