### ISSUE TITLE
elm-repl is not available in your path. Install Elm from http://elm-lang.org/.

### ISSUE THREAD

**Issue by chenpenghao** [Krzysztof-Cieslak/vscode-elm#195]
When choose a bunch of lines in VS Code:
```
x = 1
y = x + 1
z = x * y
```

and press "alt + enter", this message:

> elm-repl is not available in your path. Install Elm from http://elm-lang.org/.

will pop up.

There will be an Elm REPL window pop up, and in the window, there are:

```
'elm-repl' is not recognized as an internal or external command,
operable program or batch file.
> x = 1
| y = x + 1
| z = x * y
```

message poped up

I have already installed Elm 0.18, in Windows 10 and VS Code 1.19.2

I just wish to be able to write and run elm in real time as if in F sharp and other language.

**Comment by hakonrossebo** [comment]
Closing this as the functionality has been changed in #252. Please reopen if this is still an issue.
