### ISSUE TITLE
Please Publish 0.17

### ISSUE THREAD

**Issue by trippingtarballs** [Krzysztof-Cieslak/vscode-elm#205]
@Krzysztof-Cieslak I would like to take advantage of https://github.com/Krzysztof-Cieslak/vscode-elm/pull/196 However, this PR was merged after the latest published release of this plugin. Please can you publish 0.17 that includes https://github.com/Krzysztof-Cieslak/vscode-elm/pull/196 Thanks

**Comment by Krzysztof-Cieslak** [comment]
New version released, sorry for troubles!

**Comment by trippingtarballs** [comment]
Many thanks @Krzysztof-Cieslak Does exactly what I needed. Keep up the great work on this project 👍
