### ISSUE TITLE
Error Highlighting has stopped functioning

### ISSUE THREAD

**Issue by jonnydedwards** [Krzysztof-Cieslak/vscode-elm#209]
Hi Guys,
apologies if this is the wrong channel.
I don't know if this is just me, but error highlighting has stopped working - I've tried reinstalling vscode to stable version and a reinstallation of elm but no luck - btw thanks so much for the tooling.... totally world class :)
extension version:
0.17.0 - 26.04.2018
vscode:
Version 1.23.1
Commit d0182c3417d225529c6d5ad24b7572815d0de9ac
Date 2018-05-10T17:11:17.614Z
Shell 1.7.12
Renderer 58.0.3029.110
Node 7.9.0
Architecture x64

**Comment by Krzysztof-Cieslak** [comment]
Hey,

Is it happening on any Elm project? Or some particular code base? Also, can you please tell us what's the OS you're using. Thanks.

**Comment by jonnydedwards** [comment]
I don't know whether this helps anyone but I had 2 `elm-package.json` in my directory tree - deleting the one in the lowest folder did the trick!
