### ISSUE TITLE
Support formatSelection with elm-formatter

### ISSUE THREAD

**Issue by milesfrain** [Krzysztof-Cieslak/vscode-elm#210]
VSCode supports two formatting modes:
`editor.action.formatDocument`
`editor.action.formatSelection`

Formatting hotkeys and actions shown here:
https://code.visualstudio.com/docs/getstarted/keybindings#_rich-languages-editing

Currently, only formatting the entire document is supported. When attempting to format a selection, the following error is generated:
`There is no selection formatter for elm files installed`

I'm wondering if elm-formatter could also handle formatting a selection of text (rather than the whole file) passed through its stdin parameter.

Here's some info on the steps required to add this feature:

Add an `ElmFormatRangeProvider`.
This is similar to `ElmFormatProvider`, but implements `vscode.DocumentRangeFormattingEditProvider` instead of `vscode.DocumentFormattingEditProvider`.
https://github.com/Krzysztof-Cieslak/vscode-elm/blob/b7dc66c1f881cf4e37eb35bf48244bb2f598b416/src/elmFormat.ts#L7

Call `registerDocumentRangeFormattingEditProvider` similarly to where `registerDocumentFormattingEditProvider` is called.
https://github.com/Krzysztof-Cieslak/vscode-elm/blob/5d14ef1c573b23334596bac0db4d811f3b48d991/src/elmMain.ts#L84

Reference for `DocumentRangeFormattingEditProvider`:
https://github.com/Microsoft/vscode/blob/fbf1fefaae4235797ea398cc12e64e75b25a6cd2/src/vs/vscode.d.ts#L2818

Reference for `registerDocumentRangeFormattingEditProvider`:
https://github.com/Microsoft/vscode/blob/fbf1fefaae4235797ea398cc12e64e75b25a6cd2/src/vs/vscode.d.ts#L6882

There are probably a lot of corner cases with selecting the appropriate range to format. Maybe the selection could just be rounded up to the nearest whole lines for simplicity.

Here's a related discussion on the difference between document and selection formatting https://github.com/VSCodeVim/Vim/issues/1574

**Comment by milesfrain** [comment]
I'm going to attempt to tackle this over the next few days, but I'm not sure how long it will take to get up to speed with extension development and testing. I'm assuming the examples in this guide are a good starting point, and that this extension follows the same structure. https://code.visualstudio.com/docs/extensions/overview 
Let me know if anyone else starts working on this, so we don't duplicate our efforts.

**Comment by milesfrain** [comment]
#211 is a pull request for handling `formatSelection`.
It treats `formatSelection` the same as `formatDocument`.

---
These are some notes on the initial plan and challenges for real selection formatting support, rather than just being a document formatting wrapper.

First step is adding a `range` parameter to `elmFormat`.
* `ElmFormatProvider` passes entire document range to `elmFormat`
* `ElmRangeFormatProvider` passes selection range to `elmFormat`

I was initially planning to expand selection `range` to full lines and pass this range to elm-format, but it is tricky to preserve indentation level of blocks.

Another reason sections won't work is because elm-format inserts a module declaration at the start if one is not found.
```
module Main exposing (..)
```

So it seems that elm-format can only handle entire files, or at least files from the beginning.

The next plan was to expand `range` to include beginning of file up to last line of range selection. But this strategy fails with partial expressions, such as:
```
foo =
```

There could be some interesting ways to keep expanding selection `range` by one additional line until the elm-format stops throwing errors, but you might as well just format the entire document at that point.

So I just had the format range operation format the entire document, rather than the current selection.

The real objective of this was to just enable the `==` vim binding for selection format, without having to make a language-specific remapping, and without relying only on format-on-save.

**Comment by Krzysztof-Cieslak** [comment]
Closed by #211
