### ISSUE TITLE
Elm REPL is output only

### ISSUE THREAD

**Issue by milesfrain** [Krzysztof-Cieslak/vscode-elm#215]
When attempting to type text into the REPL, the following error appears:
`Cannot edit in read-only editor`

It makes sense that read-only is expected for the vscode "OUTPUT" tab, but it may be helpful to document this counter-intuitive behavior for new users who expect to be able to interact with this REPL the same way as the CLI REPL where you can type additional text into the prompt.

![screenshot from 2018-05-23 12-40-23](https://user-images.githubusercontent.com/3578681/40444851-bb47e20e-5e87-11e8-8930-d6ab20cdd7f1.png)

**Comment by Krzysztof-Cieslak** [comment]
In F# plugin we've moved to spawning REPL in terminal tab instead using terminal APIs. Using this method users can type into REPL. I'd be happy to accept PR.
