### ISSUE TITLE
REPL will not restart without window reload

### ISSUE THREAD

**Issue by milesfrain** [Krzysztof-Cieslak/vscode-elm#217]
When stopping REPL with `Elm: REPL - Stop`, neither `Elm: REPL - Start` nor `Elm: REPL - Send ...` will start REPL again.
The `Reload Window` command is the required workaround to allow REPL restart.

**Comment by hakonrossebo** [comment]
This has now been fixed by #252. The command to close the repl has been removed. The user can use the  "close terminal" garbage button to close the repl terminal. Closing this issue.
