### ISSUE TITLE
Unable to get the extension working - Windows 10

### ISSUE THREAD

**Issue by ser1us** [Krzysztof-Cieslak/vscode-elm#222]
Hello there

I tried to use the extension today and ran into issues.

At first it tells me it cannot find any of the elm-* commands. I double checked the env variables, tried the local installation and updated the workspace settings to point to the local node_modules installation as described in the documentation. Nothing works. The commands are available in the PATH variable, in powershell & cmd it works as expected.

After a while I thought I might as well check the developer console and sure enough, here's the error (tough I do not know what it means, sorry):

`[Extension Host] Activating extension 'sbrink.elm' failed: Cannot find module 'hawk'.
t.log @ console.ts:136`
`extensionService.ts:870 Activating extension 'sbrink.elm' failed: Cannot find module 'hawk'.
w._logMessageInConsole @ extensionService.ts:870`
`console.ts:136 [Extension Host] Activating extension `sbrink.elm` failed:  Cannot find module 'hawk'`

> Version 1.24.1
> Commit 24f62626b222e9a8313213fb64b10d741a326288
> Date 2018-06-13T17:51:32.889Z
> Shell 1.7.12
> Renderer 58.0.3029.110
> Node 7.9.0
> Architecture x64

Let me know if I can provide you with more information!

Cheers,
Christoph

**Comment by Krzysztof-Cieslak** [comment]
This looks like a problem with installation, please try to remove extension (and check if there is nothing left in VSCode's extension folder) and install it again.

**Comment by ser1us** [comment]
I installed the extension on another computer the other day and there it's working fine... let me close this issue for now. If it happens again I let you know. Thanks for this great extension by the way!
