### ISSUE TITLE
Highlighting on Save doesn't refresh on Save on Mac

### ISSUE THREAD

**Issue by jlengrand** [Krzysztof-Cieslak/vscode-elm#228]
Hey there, 

I have a 2017 MBP. 
When I write elm with an issue, the extension does indicate what the issue is without worries. However, once the error is fixed, the view doe snot seem to refresh any more on save. I have to restart Visual Code for the view to update. 

Closing the pane and reopening the file also does not suffice. Is that a known issue? 

<img width="923" alt="screen shot 2018-07-21 at 11 56 13 am" src="https://user-images.githubusercontent.com/921666/43034472-54406bc4-8cdd-11e8-9acf-95bcc4641522.png">

I looked but found no compelling message or debug info that could indicate what the issue is. 

Thanks,

**Comment by jlengrand** [comment]
After a couple minutes, my files look completely crazy because of this. And this even though the project actually compiles fine 

![Uploading Screen Shot 2018-07-21 at 12.46.55 PM.png…]()

**Comment by sentience** [comment]
I've just begun seeing this too after this working normally for me last week. I'm using VS Code Insiders version; perhaps they pushed a change that broke this?

Since the symptoms are so similar, I tried the fix in #225. That change seems to fix this issue too!

**Comment by jlengrand** [comment]
Ha yes, it's good mentioning that I use insiders as well. Let me try the normal version.

**Comment by jlengrand** [comment]
Yes, I can validate that the issue **only happens on VsCode Insiders edition**. Normal install behaves as expected

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #225

**Comment by jlengrand** [comment]
Great, thanks!
