### ISSUE TITLE
Handling of <| with new grammar updates

### ISSUE THREAD

**Issue by Punie** [Krzysztof-Cieslak/vscode-elm#232]
Before the 0.19.0 update, forward and backward pipes where handled correctly.

However, since then, the backward pipe `<|` (under certain color themes) has the `|` part colorized differently from the `<` part. The forward pipe `|>` is unaffected (see screenshots).
<img width="61" alt="screen shot 2018-07-30 at 17 13 02" src="https://user-images.githubusercontent.com/13525570/43406272-281038f4-941c-11e8-99a7-73da94d548d5.png">
<img width="144" alt="screen shot 2018-07-30 at 17 14 05" src="https://user-images.githubusercontent.com/13525570/43406273-2828b302-941c-11e8-8515-8ec4ae733202.png">

Unfortunately, this breaks the rendering of code ligatures as well.

**Comment by Punie** [comment]
I tried fiddling with the order of the infix operators matching here :
https://github.com/Krzysztof-Cieslak/vscode-elm/blob/master/syntaxes/elm.json#L386
and it seems to work just fine.

I'll see if I can make a PR when I get the chance.

**Comment by cmditch** [comment]
![image](https://user-images.githubusercontent.com/15849320/43418415-0b9a6238-93fb-11e8-840c-a3b029b6cb29.png)
Yea, experiencing a number of breakages related to this as well.

Backward pipe coloring, import coloring `Route.link` should have `Route` be orange, and underscores are greyed out as well.

**Comment by Krzysztof-Cieslak** [comment]
CC: @mdgriffith

**Comment by Punie** [comment]
I believe this is closely related to #233, perhaps we should keep only one of those open.

**Comment by mdgriffith** [comment]
Ah, yeah this one was slightly different.  @Punie you're right it was that `<` was capturing that character before the `<|` could match.  I've fixed it in my other changes and will make a PR soon.

**Comment by Punie** [comment]
@mdgriffith Thanks for the update and the PR !
Did you however get the chance to check if there was any other operator that might have suffered the same priority matching issues ?
If not, I'll see if I can make some tests with other operators (I would find it kinda odd of `<|` was the only one affected by this) and post my findings here.

In any case : awesome work !

**Comment by mdgriffith** [comment]
Good call!  I just checked and both `<=` and `>=` were also affected.  I've adjusted the regex.  I believe all the operators should be good now.
