### ISSUE TITLE
Duplicated function suggestions

### ISSUE THREAD

**Issue by jackfranklin** [Krzysztof-Cieslak/vscode-elm#237]
Hey,

Firstly, thank you for your work on this plugin!

I'm seeing an odd thing where I'm getting a lot of suggestions for functions duplicated in the intellisense list:

<img width="534" alt="screen shot 2018-08-09 at 21 00 04" src="https://user-images.githubusercontent.com/193238/43922801-b9d6593c-9c17-11e8-9a8d-2a8872d81400.png">

What's interesting is that it doesn't do it when I've only typed the module name, but the moment I hit `.` and go to type the function name, it does:

<img width="537" alt="screen shot 2018-08-09 at 21 04 04" src="https://user-images.githubusercontent.com/193238/43922835-d40c6242-9c17-11e8-98f3-f445ea75f4f6.png">

<img width="541" alt="screen shot 2018-08-09 at 21 04 10" src="https://user-images.githubusercontent.com/193238/43922838-d7b89d7a-9c17-11e8-8588-d4d1fde61a07.png">

I can't seem to figure what's going on here unfortunately and wondered if you could shed some light - I'm happy to try to fix if I can have a nudge in the right direction!

**Comment by jackfranklin** [comment]
I thought it might be a case of checking for duplicates here: https://github.com/Krzysztof-Cieslak/vscode-elm/blob/master/src/elmAutocomplete.ts.

But it could be Elm Oracle related?

**Comment by Krzysztof-Cieslak** [comment]
Can't reproduce anymore, I'll assume it got fixed while fixing some other problems.
