### ISSUE TITLE
Running elm-format fails upon saving large files.

### ISSUE THREAD

**Issue by oktay-sen** [Krzysztof-Cieslak/vscode-elm#240]
I have elm-format installed globally, and `editor.formatOnSave` is enabled, yet formatting on save fails for large files only. For small files it works fine, and running elm-format manually on large or small files also works. The error message is `Running elm-format failed. Install from https://github.com/avh4/elm-format and make sure it's on your path`.

**Comment by hakonrossebo** [comment]
To verify - have you tried to extend the timeout in this setting?

"[elm]": {
    "editor.formatOnSave": true,
    "editor.formatOnSaveTimeout": 1500
},

**Comment by Krzysztof-Cieslak** [comment]
Using the settings provided above is a correct workaround.
