### ISSUE TITLE
Backwards pipe (<|) Fira Code ligature doesn't work in some themes

### ISSUE THREAD

**Issue by jcmrva** [Krzysztof-Cieslak/vscode-elm#241]
...unless the line is commented out:
![image](https://user-images.githubusercontent.com/20140997/44007353-a5c1fa5e-9e61-11e8-81b6-c2969501e7f9.png)

Looks normal in Ionide:
![image](https://user-images.githubusercontent.com/20140997/44007358-d3c4be1e-9e61-11e8-9660-5d9334a7119d.png)

That's the Night Owl theme, but the issue isn't isolated to it. Switching to some others (e.g. Abyss) makes it work:
![image](https://user-images.githubusercontent.com/20140997/44007444-66db98fc-9e63-11e8-8089-22e71da48019.png)

It's an extremely minor issue and I don't use them often. I'm mostly curious how it could be happening. Latest versions on everything, of course.

**Comment by FrostedMint** [comment]
This is happening because the colors of the two characters are different. The `<` is cyan, the `|` is purple. I believe this prevents the ligature from forming.

**Comment by Krzysztof-Cieslak** [comment]
I think this will be solved in the next version of the plugin - it will include some grammar fixes.

**Comment by Krzysztof-Cieslak** [comment]
Should be fixed by #235
