### ISSUE TITLE
Adding packages fails in elm 0.19

### ISSUE THREAD

**Issue by noelrappin** [Krzysztof-Cieslak/vscode-elm#246]
Adding packages from the command line currently fails because the elm 0.19 package command asks for a [Y/n] approval before installing and there's no mechanism for entering that approval.

**Comment by ashishsc** [comment]
This may have been fixed in https://github.com/Krzysztof-Cieslak/vscode-elm/commit/615f27ba086e923187d761780b08e4933db9be81

**Comment by hakonrossebo** [comment]
This is a known issue - I asked on Slack, but it seems like we have to change output to terminal with ability to press y/n. Luke suggested using echo "y" | command, but that would also require the terminal. Looking into terminal for repl at the same time.

**Comment by Krzysztof-Cieslak** [comment]
I guess we could read output from the i/o and just send `Y` whenever it ask for it. Or ask user with pop up message
