### ISSUE TITLE
Writing tests with Elm 0.19

### ISSUE THREAD

**Issue by ozmat** [Krzysztof-Cieslak/vscode-elm#248]
With Elm 0.19 and the new `elm.json`, tests don't need to have their own `elm-package.json` anymore :

```
{
    "type": "package",
    ...
    "elm-version": "0.19.0 <= v < 0.20.0",
    ...
    "test-dependencies": {
        "elm-explorations/test": "1.0.0 <= v < 2.0.0"
    }
}
```

But when writing tests in vscode, it seems like `vscode-elm` (when running `elm-format`) is not aware of those `test-dependencies` :

```
UNKNOWN IMPORT - The Tests.Validation module has a bad import:

    import Test

I cannot find that module! Is there a typo in the module name?

When creating a package, all modules must live in the src/ directory.
```

Running everything outside of vscode works fine :

```
$ elm-format -h
elm-format-0.19 0.8.0
...

$ elm-format --validate tests/
[]

$ elm-test
Success! Compiled 1 module.
Success! Compiled 1 module.

elm-test 0.19.0-beta4
---------------------

Running 43 tests. To reproduce these results, run: elm-test --fuzz 100 --seed 2035616301


TEST RUN PASSED
...
```

But it would be nice to have `vscode-elm` aware of those `test-dependencies` just like `elm-format` is (I suppose that now `elm-test` is generated in the same/root `elm-stuff` folder and that's how `elm-format` is aware of the `Test` module).

**Comment by jackfranklin** [comment]
I asked about this in sslack, the plan is that `elm-test` will provide its own `make` function that we can call whenever we detect that we're in a tests file (or the `tests` directory).

```
I'm planning to add an `elm-test make` which takes care of this for test files

which editors can then run instead of `elm make` when they detect that they're in the `tests/` directory
```

**Comment by noelrappin** [comment]
Looks like this has been done: https://github.com/rtfeldman/node-test-runner/issues/284

**Comment by Kurren123** [comment]
I'm guessing the right place to look here is `elmMake.ts`, to return a different `makeCommand` if this is elm 0.19 and we're in the tests folder?

**Comment by jackfranklin** [comment]
I have created a PR for this #286  :)
