### ISSUE TITLE
Hover info broken with Elm 0.19

### ISSUE THREAD

**Issue by r1sc** [Krzysztof-Cieslak/vscode-elm#260]
The hover info feature does not work with Elm 0.19.
Applies to vscode-elm 0.20

I can't seem to get the hover info to show up when hovering over any function (even core package functions). This worked in 0.18, so I suspect the 0.19 update broke this somehow.

To reproduce:
1. With Elm 0.19 installed and **0.18 uninstalled** - open any Elm-file in VSCode.
2. Hover over any function. Nothing appears.

**Comment by 7sharp9** [comment]
Yep this is a known issue, unlikely to fixed any time soon due to the
Oracle being relatively unmaintained.

**Comment by r1sc** [comment]
I took a peek at elm-oracle and it seems to be built on an old version of Elm - specifically one that allows Native modules. Is there any support packages in the Elm compiler we can make use of to build a new oracle that doesn't depend on various unsupported things?

**Comment by hakonrossebo** [comment]
I fixed this partly in this latest release by omitting elm-oracle for 0.19. This makes hover and autocomplete work for your source, but not not external packages.

**Comment by r1sc** [comment]
PR #265 fixes this. I guess we can close this one.
