### ISSUE TITLE
Slows down webpack-dev-server significantly

### ISSUE THREAD

**Issue by Naatan** [Krzysztof-Cieslak/vscode-elm#261]
I run webpack-dev-server on our project with the `--watch` argument, which auto reloads the dev server when I make changes. When I run this without vscode it takes 2 seconds to rebuild Elm. When I run this with vscode and this addon it takes upwards of 8 seconds. 

I have noticed whenever I save a file vscode hangs for a little, presumably because it's linting my code. Thing is running `elm-make` directly is very fast, so I'm not sure why it's consuming so many resources.

Not sure what the exact cause is here, but my guess is the linter. If you can instruct me how to turn it off or delay it then I could validate that assumption.

Thanks

**Comment by hakonrossebo** [comment]
You could change the user configuration settings for either elm.compiler="elm_disable_by_incorrect_name" or the same for elm.makeCommand if you're on 0.18. You should only get a message saying compiler command not found.
