### ISSUE TITLE
"The 'elm-make' compiler is not available." elm.makeCommand issue

### ISSUE THREAD

**Issue by DanL** [Krzysztof-Cieslak/vscode-elm#268]
Hi folks - after updating to the latest version of this plugin (0.21.0), I started getting the following error on save (Elm 0.18.0):

`The 'elm-make' compiler is not available. Install Elm from http://elm-lang.org/.`

Once I changed `elm.makeCommand` from `elm make` to `elm-make` it started working again. Both commands manually worked fine in my terminal.

I'm just noting this here since it will likely affect other people, and it's non-obvious that this is the correct fix.

**Comment by hakonrossebo** [comment]
There is a pr #262 that fixes this issue and will come in the next release

**Comment by DanL** [comment]
Cool! Thanks for your hard work.
