### ISSUE TITLE
Is elm documentation 19 supported?

### ISSUE THREAD

**Issue by Maxim-Filimonov** [Krzysztof-Cieslak/vscode-elm#269]
Environment:
elm 0.19
vscode  1.26.1
vscode-elm 0.21.0

I don't seem to be able to figure out how to make documentation work or any intellisence.
See this gif for reproduction of the issue.
![doy6iov2nj](https://user-images.githubusercontent.com/360645/45104431-c704cc00-b13a-11e8-8168-d2ae391c0aaf.gif)

**Comment by hakonrossebo** [comment]
If you mean documentation by "hover", this is currently supported for you own code. Support for external packages and Elm core are coming in the next release - see #265

**Comment by Maxim-Filimonov** [comment]
@hakonrossebo just tested it locally and it works, great ! 👍 
I'll close the issue as it seem duplicate.
