### ISSUE TITLE
can't find elm-make after upgrade to v19

### ISSUE THREAD

**Issue by dschinkel** [Krzysztof-Cieslak/vscode-elm#271]
How do we fix this (see the lower-right of my screen shot)?  I'm running elm 19 and already re-ran `npm install -g elm-format`

<img width="346" alt="screen shot 2018-09-18 at 6 26 50 pm" src="https://user-images.githubusercontent.com/338798/45724694-fd037080-bb7c-11e8-8b39-2eb06e4e0e97.png">

<img width="1440" alt="screen shot 2018-09-18 at 7 40 35 pm" src="https://user-images.githubusercontent.com/338798/45724661-dd6c4800-bb7c-11e8-889b-92d45b0ad988.png">

**Comment by andys8** [comment]
Same for me, but I'm running elm still in version `0.18`.

**Comment by hakonrossebo** [comment]
Are you using vscode-elm? The extension you  are showing seems to be jackfranklin-elm? Not sure if that is updated to 0.19. Also - are you using this in a 0.19 project? If so, the extension should work as expected.

**Comment by hakonrossebo** [comment]
@andys8 - there is a bugfix coming in the next release for 0.18. In the meantime, you can change the elm-make setting to "elm-make" instead of "elm make"

**Comment by andys8** [comment]
@hakonrossebo Thanks for the workaround!

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `0.22.`
