### ISSUE TITLE
Improvement: Parse elm version

### ISSUE THREAD

**Issue by andys8** [Krzysztof-Cieslak/vscode-elm#273]
### Issue

Currently the elm version detection checks for existence of `elm.json` or `elm-package.json` files, but doesn't read the content. This will not work without changes for future elm versions. https://github.com/Krzysztof-Cieslak/vscode-elm/blob/2f50c1cedc3495ab56ec8b67a8d579f7e2adeaac/src/elmUtils.ts#L129

### Solution

Parse `elm.json` file and read the `elm-version` field. 

### Open Questions and Feedback
Is it a valid idea? Will it have an impact on performance? Is it relevant to know the elm version (in the future)?

**Comment by Krzysztof-Cieslak** [comment]
It doesn't seem like it is necessary at the moment. We may come back to it if it will be needed for next language version, but we'll handle it when we'll actually have this problem... Closing for now.
