### ISSUE TITLE
Format Document is not working

### ISSUE THREAD

**Issue by malaire** [Krzysztof-Cieslak/vscode-elm#281]
I'm using VS Code in Debian Stable.

When I press Ctrl-Shift-I or select "Format Document" from right click menu, nothing happens.

I have elm-format on path, and I have not changed any of the related settings.

**Comment by malaire** [comment]
I didn't have any folder added to my workspace. Once I added a folder, elm-format started to work.

But there is no mention anywhere that folder is required, so I still think this is a bug.

**Comment by Krzysztof-Cieslak** [comment]
Running in folder is general assumption for the plugin. Closing as "by-design"
