### ISSUE TITLE
Errors are not highlighted/detected after update to 0.23

### ISSUE THREAD

**Issue by CarstenKoenig** [Krzysztof-Cieslak/vscode-elm#289]
after VS.code updated the plugin to 0.23 today it stopped showing/detecting highlighting:

- in the file errors are not highlighted
- in the problems pane no errors are shown
- in the project folder files with errors are not marked red any more

Things like using elm-format, showing type-infos, etc. seem to work still.

As far as I can tell you can easily reproduce this problem by creating or opening a new Elm project (seems to be a problem in both elm-0.18 and elm-0.19) and producing some errors.

**Comment by Y0hy0h** [comment]
I noticed that running the `Elm: Make` command also fails. So it seems that it doesn't find the elm executable anymore or something goes wrong during the call.

**Comment by CarstenKoenig** [comment]
that's not the case for me - I use local install and call it via `./node_modules/.bin/elm` - if I use misspell that in the settings then everything including tooltips stop working

and yes - I downgraded too and this resolves the issue

**Comment by jackfranklin** [comment]
@CarstenKoenig would you mind sharing your plugin settings ? 

I just had this problem locally but it was because I was setting the `compiler` setting to `yarn elm`, which, because it's two words, seems to cause problems.

Once I set `elm.compiler` to `./node_modules/.bin/elm` it all works fine, so I'm not sure what the issue is here :/

**Comment by CarstenKoenig** [comment]
@jackfranklin my settings are more or less the same - it's on windows so it's `.\node_modules\.bin\elm` and `.\node_modules\.bin\elm-format` ...

I also tried global installed elm (just `elm` and `elm-format`) and even tried elm-0.18 (only locally though)

- I could reproduce this issue both with existing projects and fresh ones.
- I tried to remove `elm-stuff`, `node_modules` - no difference
- I looked through all the VS.code logs I could find - *nothing*
- I enabled the developer-tools but there was nothing Elm-related in the console at all
- All the elm related output-channels(?) in VS.code (Elm reactor, Elm analyze, Elm make) are empty as well

---

once I reverted back to 0.22 all worked just as it did the day before

---

I would happily provide more logs/feedback - if there is some kind of debug setting for the plugin I'm willing to give it another go

**Comment by jackfranklin** [comment]
@CarstenKoenig I'm trying to figure out what changed between releases :/

What file are you editing? Is it a test file ? What's the directory structure like?

**Comment by rceuls** [comment]
I have the same issue: I use Elm 0.19 on windows (installed via the installer) which is on my PATH (and callable from the terminal in vscode). I tried with an existing project which works in 0.22 and two new ones (via create-elm-app and elm init); all three have the same issue (no error highlighting, no problems in the error pane, ...) that @CarstenKoenig  has. If I revert the plugin all three work.

**Comment by CarstenKoenig** [comment]
@CarstenKoenig the structure in all my tests where basically like this:

- `elm.json` in the main folder - the one I open with VS.code
- `src` directory just inside this where all the `.elm` files are

it was no test file - I was looking forward to test this feature but I did not get that far

**Comment by CarstenKoenig** [comment]
maybe it's a windows thing (I try to test this on Linux later if you like) - from the usual suspects I can think of:

- path to long? No not as far as I can tell - the longest one has < 100 chars
- casing in path - well Windows does not care so I think this should be an non-issue - anyway files and paths under the project seems all to be in order

so I can think of no further hints I could give you

**Comment by jackfranklin** [comment]
@CarstenKoenig at this point I'm leaning towards it being a Windows thing, but I'm not going to be able to test. Basing that on all the people in this thread reporting it are on Windows, and I can't replicate on my Macbook. If you are able to debug / run the plugin locally and try to get some more info that'd be great.

**Comment by jackfranklin** [comment]
This is what changed between versions:

https://github.com/Krzysztof-Cieslak/vscode-elm/compare/0.22.0...0.23.0

Might be worth seeing if we can spot any suspicious changes, especially around Windows-specific code.

**Comment by CarstenKoenig** [comment]
I just did a quick test on *Linux* and **yes** it works there.

Can you give me some help on how I can go and test this? Can I do this using the VS.code developer tools? If yes at which module/source-file should I look first?

Sadly now I'm home where I have no Window system running but I can have a look at it tomorrow.

**Comment by jackfranklin** [comment]
@CarstenKoenig I would clone this locally and run it, and start adding lots of console.logs everywhere.

My hunch is that this might be happening in `src/elmLinter.ts`, specifically where we do `cp.exec` to run `elm make`, but I'm not 100%.

**Comment by CarstenKoenig** [comment]
ok I try and see if I can get this working - for some reason I think that maybe this might be a line-ending problem (I noticed you split by `\n` for example) - maybe for some reason windows-style line endings get in the way now (?)

**Comment by jackfranklin** [comment]
Ah that's a good point - it could well be that. I think we should probably try to always split by OS-specific line ends (I think Node has a built in thing to tell us what the OS line endings are).

**Comment by Krzysztof-Cieslak** [comment]
First of all, sorry everyone for this problem - I'm mostly developing on MacOS nowadays, but I *should* test it on windows before releasing. 

> My hunch is that this might be happening in `src/elmLinter.ts`

I think it's pretty good guess given that only thing that's not working is error reporting. I'll try to take a look later today.

**Comment by r1sc** [comment]
Yes, I narrowed it down to line 133 in ```src/elmLinter.ts``` https://github.com/Krzysztof-Cieslak/vscode-elm/blob/85e22d8c3f9eb2339c0841d4d7574762be794624/src/elmLinter.ts#L133

If I remove this then it works on Windows.

**Comment by r1sc** [comment]
To get this working right away, change line 87 in ```sbrink.elm-0.23.0/out/src/elmLinter.js``` to 
```const isTestFile = false; //elmTest.fileIsTestFile(filename);```

This will probably break other things, but in the meantime this works for me :)

**Comment by r1sc** [comment]
I think I figured it out. ```utils.detectProjectRootAndElmVersion``` don't like " (quote-characters) in the filename. The linter does this before asking elmTest whether it's a test-file:

```
if (utils.isWindows) {
    filename = '"' + filename + '"';
}
const isTestFile = elmTest.fileIsTestFile(filename);
```

By simply rearranging ```const isTestFile = elmTest.fileIsTestFile(filename);``` above the filename mutation, it works as it should.

**Comment by CarstenKoenig** [comment]
thank you!

**Comment by Krzysztof-Cieslak** [comment]
Hey, I've just published 0.24.0 with suggested fix, please let me know if it fixes the problem for you. Thanks a lot for all debugging!

**Comment by jackfranklin** [comment]
Nice, thanks for the fix, and sorry that I was the one who introduced the bug 😢

**Comment by CarstenKoenig** [comment]
I'll try this first thing tomorrow morning - thanks a lot

**Comment by Y0hy0h** [comment]
I had this issue before and a quick test indicate that it works now. Thank you all for working on this!

**Comment by rceuls** [comment]
Seems to work, thanks for the quick fix 👌

**Comment by CarstenKoenig** [comment]
Works for me in 0.24.0 too

thank you all!

**Comment by shamansir** [comment]
That's a bit amusing, but Elm 0.18 errors are not highlighted for me in v0.24 anymore. And so I have to install v0.23 from VSIX. And I use Mac OS X.

**Comment by CarstenKoenig** [comment]
@shamansir oh - I have to admit I did not try this (we updated most of our projects to 0.19 by now) - maybe we should reopen the issue?

**Comment by shamansir** [comment]
@CarstenKoenig I've managed to find the source of the error and it seems to be different from what was discussed here, since it can be caused by `elm-module-parser`:

```
[Extension Host] Here is the error stack:  /Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/parsers/elm_module_parser.js:232
/private/var/folders/vf/6_v784pj3mg3ryt3rc5f71_c0000gn/T/AppTranslocation/A…dio Code.app/Contents/Resources/app/out/vs/workbench/workbench.main.js:263 [Extension Host] Here is the error stack:  /Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/parsers/elm_module_parser.js:232
              ...name,
              ^^^
SyntaxError: Unexpected token ...
	at createScript (vm.js:53:10)
	at Object.runInThisContext (vm.js:95:10)
	at Module._compile (module.js:543:28)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
	at Function.o._load (/private/var/folders/vf/6_v784pj3mg3ryt3rc5f71_c0000gn/T/AppTranslocation/A29C9F8E-3C58-4F2A-9699-09F6FBC88B00/d/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:696:771)
	at Module.require (module.js:498:17)
	at Module.patchedRequire [as require] (/private/var/folders/vf/6_v784pj3mg3ryt3rc5f71_c0000gn/T/AppTranslocation/A29C9F8E-3C58-4F2A-9699-09F6FBC88B00/d/Visual Studio Code.app/Contents/Resources/app/extensions/git/node_modules/diagnostic-channel/dist/src/patchRequire.js:14:46)
	at require (internal/module.js:20:19)
	at Object.loadParser (/Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/src/util.js:11:19)
	at Object.<anonymous> (/Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/src/module_parser.js:4:32)
	at Object.<anonymous> (/Users/shamansir/.vscode/extensions/sbrink.elm-0.24.0/node_modules/elm-module-parser/dist/src/module_parser.js:36:3)
	at Module._compile (module.js:571:32)
	at Object.Module._extensions..js (module.js:580:10)
	at Module.load (module.js:488:32)
	at tryModuleLoad (module.js:447:12)
	at Function.Module._load (module.js:439:3)
...
```

The minified source in my case contains these lines in `workbench.main.js`:

```js
                getDuration: function(e, t) {
                    const n = global._performanceEntries;
                    let i = e
                      , r = 0;
                    for (let o = 0; o < n.length; o += 4)
                        if (n[o + 1] === i) {
                            if (i !== e)
                                return n[o + 2] - r;
                            i = t,
                            r = n[o + 2]
                        }
                    return 0
                },
                importEntries: function(e) {
                    global._performanceEntries.splice(0, 0, ...e) // <-- could be the source of the error
                },
                exportEntries: function() {
                    return global._performanceEntries.slice(0)
                }
```

**Comment by shamansir** [comment]
In my case, only the syntax is highlighted and no type hints or errors are displayed (since extension is not loaded at all) so maybe it's the different issue indeed.
