### ISSUE TITLE
Outdated snippets for elm 0.19

### ISSUE THREAD

**Issue by RosarioPulella** [Krzysztof-Cieslak/vscode-elm#302]
Some snippets provide invalid code for elm 0.19. For example the `Html.program` snippet imports `Html` for the `Html.program` method. With elm 0.19 `Html.program` is no longer available. Maybe the snippet and related snippets should import `Browser` and use `Browser.application` .

**Comment by tretum** [comment]
I have added snippets for sandbox, element, document and application in #306.

**Comment by RosarioPulella** [comment]
Awesome Thanks!
