### ISSUE TITLE
Send to Elm-Repl Keyboard shortcuts

### ISSUE THREAD

**Issue by csmith111** [Krzysztof-Cieslak/vscode-elm#43]
I am not able to get the "send to REPL" keyboard shortcut to work? I want to send a selection to the REPL which is Alt+Enter (?), do I have to do something to enable the keyboard short cuts for the REPL? 
(If I use the command palette it seems to work fine.)

**Comment by stkb** [comment]
Are you doing this from something other than an .elm file? I can't reproduce the problem when sending a selection from an elm file. If you do it from any other sort of file then the command might not work at all, which is a separate bug that I'll get on to fixing.

**Comment by Krzysztof-Cieslak** [comment]
Also, there might be problem with other extension overriding same keyboard shortcut.

**Comment by csmith111** [comment]
@stkb Thank you for your response. I am using an elm file and still the (Alt-Enter) short cut does not work. (If I use the command palette it seems to work fine.)
@Krzysztof-Cieslak  is there a way that I can check if some other extension is overriding it?
I think it is the ionoide F# extension as that has an Alt Enter command too. 
If I want to disable this extension is there a way to do it base on the file i.e, disable for .elm files? 

Since the file is a .elm file I would have thought that the vscode-elm should take precedence? Is that right?

**Comment by rmunn** [comment]
I'm having the keybinding conflict problem in the opposite direction: I have both Ionide and the Elm extension installed in VS Code, and when I'm editing a `.fs` file, hitting Alt-Enter brings up the warning "No handler found for the command: 'elm.replSendSelection'. An extension might be missing an activation event."

I would expect that in a `.fs` file, Ionide's Alt-Enter keybinding would "win", while in a `.elm` file Elm's keybinding would "win". Instead, Elm is trying to handle Alt-Enter events when I'm editing a `.fs` file.
