### ISSUE TITLE
Click to goto decleration

### ISSUE THREAD

**Issue by ccapndave** [Krzysztof-Cieslak/vscode-elm#45]
(Feature request!)  It would be wonderful if you could click on something with the `cmd` key held down and VSCode would navigate to the declaration of the symbol (just like it does for Typescript).

**Comment by popara** [comment]
I am verbally +1 oning this one.
And if somebody can point me how to help to implement it, I would dedicate effort do it. 
[never worked on VS Exts]

**Comment by gak** [comment]
@popara I found an example that might help: https://github.com/Microsoft/vscode-go/blob/master/src/goDeclaration.ts#L156

**Comment by popara** [comment]
Nice, now I get the idea where to start from! :)
Give me weekend or two and shall be done :)

**Comment by Krzysztof-Cieslak** [comment]
Implemented in `0.13.0`

**Comment by popara** [comment]
Amd works like charm. 
U rock! 
<3
