### ISSUE TITLE
Elm keybinding conflicts with built-in keybinding "Select All Occurences of Find Match"

### ISSUE THREAD

**Issue by beckler** [Krzysztof-Cieslak/vscode-elm#59]
Not sure what the elm keybinding does, but it seems to conflict with "Select All Occurences of Find Match", which is currently defaulted to Alt+Enter.

**Comment by beckler** [comment]
Could be related to #43

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `0.11.1`
