### ISSUE TITLE
The 'elm-make' compiler is not available.

### ISSUE THREAD

**Issue by tjbo** [Krzysztof-Cieslak/vscode-elm#65]
I get this error every time I save a file, however it does build...

On Mac, OSx

**Comment by chalmagean** [comment]
I also get this if I change the `"elm.makeCommand": "elm-make"` setting. I wanted to have warnings (`"elm.makeCommand": "elm-make --warn"`) and that gives me the same error you mentioned.

**Comment by Xananax** [comment]
I also have this error, Arch Linux. I cannot build either, though.

Elm and related things such as elm-make are available in my `$PATH`.

**Comment by robertohuertasm** [comment]
In my case, using Ubuntu 16.04, I solved it by setting the path in the `.bash_profile` file. It seems that `vscode` uses it. If you set it only in your `.bashrc` you may see it in your path when using the terminal but `vscode` will miss the path and you'll get the error.

**Comment by Krzysztof-Cieslak** [comment]
This can be fixed either by adding `elm-make` to `$PATH` or by setting `elm.makeCommand`

**Comment by rofrol** [comment]
Somehow `elm-format` and `elm-make` are not visible in vscode, even though are in `$PATH`.

I needed specify full paths in settings:

```json
{
    "elm.formatCommand": "/Users/user/bin/elm-format",
    "elm.makeCommand": "/usr/local/bin/elm-make"
}
```
