### ISSUE TITLE
Feature request include an "Add" button when warning about a missed type annotation.

### ISSUE THREAD

**Issue by 7sharp9** [Krzysztof-Cieslak/vscode-elm#73]
The lighttable Elm plugin has this and it works nicely:

<img width="676" alt="screen shot 2016-07-28 at 19 40 32" src="https://cloud.githubusercontent.com/assets/588746/17225080/6acc519e-54fb-11e6-91b1-3bc0f822c646.png">

**Comment by 7sharp9** [comment]
(Clicking `Add` adds the type annotation to your code)

**Comment by Krzysztof-Cieslak** [comment]
There is no API for modifying tooltips this way.

But we should be able to add light bulb suggestion with fix.

**Comment by hakonrossebo** [comment]
I suggest we also close this issue. The vscode idiomatic way for this functionality is to show the quick fix. Based on linting warnings, this is implemented in #129 - code actions.

**Comment by ShalokShalom** [comment]
Yeah, this is solved?

**Comment by thitemple** [comment]
It seems to be working.

[http://g.recordit.co/jFspSfWAs3.gif](url)
