### ISSUE TITLE
Error highlighting does not work when folder name has spaces

### ISSUE THREAD

**Issue by LittleBrainz** [Krzysztof-Cieslak/vscode-elm#75]
I am presently working through the tutorials from https://github.com/knowthen/elm. Some of the examples in this project are in folders which have spaces in the folder name.

Error highlighting does not work when the containing folder name (or the file name) has spaces, but otherwise works fine.

I am on Windows 10.

**Comment by rcapraro** [comment]
I have the same issue. I am on Windows 10.

**Comment by Rud156** [comment]
I too have to same issue.

**Comment by Krzysztof-Cieslak** [comment]
Fixed by #197
