### ISSUE TITLE
vscode-elm does not work with a local project install of Elm

### ISSUE THREAD

**Issue by LittleBrainz** [Krzysztof-Cieslak/vscode-elm#77]
Even when coding in Elm, I use an NPM "package.json" to to insure all project dependencies are immediately available to anyone downloading one of my repos. So naturally, I list "elm" in "devDependencies".

Prior to upgrading Node, I like to clear out my global NPM packages (which included "elm"). I then found that vscode-elm no longer worked (or at least no longer provided error highlighting).

After doing a "npm install -g elm", all functionality was restored.

I am on Windows 10.

**Comment by Krzysztof-Cieslak** [comment]
This should be fixed in some recent version.
