### ISSUE TITLE
elm-repl: command not found

### ISSUE THREAD

**Issue by danobri** [Krzysztof-Cieslak/vscode-elm#79]
When I try to start elm-repl within VSCode, it can't find the command.  I am on a Mac and installed Elm with the Mac installer.  If I open a terminal window, I have to use sudo in order to use elm-repl and the other CLIs, so thought maybe I had to launch VSCode with sudo.  I tried that but still get the same error.  I also get occasional warnings in VSCode saying "The 'elm-make' compiler is not available.  So for some reason VSCode can't find my Elm install.  Any idea what the issue is?

**Comment by FoggyFinder** [comment]
@danobri Probably you have not set the path environment

**Comment by Krzysztof-Cieslak** [comment]
This should be solved by adding Elm to the PATH.
