### ISSUE TITLE
Unable to start REPL

### ISSUE THREAD

**Issue by simax** [Krzysztof-Cieslak/vscode-elm#80]
Just installed `Visual Studio Code` version `1.5.3`  on `Windows 10` then installed the `elm language support` extension version `0.8.1`

When I try to run the `ELM - REPL start` command from the `command pallete` I get the following error:

`Cannot read property 'stdin' of undefined` so the `REPL` doesn't start.

**Comment by FoggyFinder** [comment]
The same problem. But the command "Send Selection" works as it should despite the error window.

**Comment by quintusm** [comment]
I am also experiencing the issue.  VSCODE v1.7.2, Node6.5.0 and elm extension 0.8.3

**Comment by OzTK** [comment]
You have to open a folder before trying to launch the REPL. I think a context is needed

**Comment by bjadamson** [comment]
I just ran into this on Windows 7, I don't understand what opening a folder does, or what that really means given this context. I bound a keyboard shortcut to open a new repl instance, and hit it while editing a file.

When I do that, I get the same error message the other users are getting. Would you mind expanding on your answer @OzTK ? Is this some kind of work-around for a known bug?

Thanks for your time!

**Comment by Krzysztof-Cieslak** [comment]
I think that general assumption of the plugin is that work is done with folder opened in VSCode, and we don't really support single in-memory file.
