### ISSUE TITLE
Command 'elm.make' not found when pressing cmd+f5 in a non-Elm project

### ISSUE THREAD

**Issue by TimonVS** [Krzysztof-Cieslak/vscode-elm#84]
The command + f5 keybinding is used to run the project without debugging. `vscode-elm` has set the keybinding to run `elm.make`. The problem is that it does this even when you're not using Elm in your project.

I'm now forced to uninstall the Elm extension because VS Code doesn't have the ability to disable extensions yet.
This problem can probably be solved by using a `when` clause for the keybindings (https://code.visualstudio.com/docs/customization/keybindings#_when-clause-contexts).

**Comment by Krzysztof-Cieslak** [comment]
Fixed in `0.11.1`
