### ISSUE TITLE
Self Closing Quotation Marks

### ISSUE THREAD

**Issue by IamEchelon** [Krzysztof-Cieslak/vscode-elm#85]
Quotes don't automatically self close.

**Comment by kojuro-kun** [comment]
I can do this one. I am thinking to implement using the hook:
`vscode.workspace.onDidChangeTextDocument(event => ())` unless there is a better way?

**Comment by kojuro-kun** [comment]
Actually appears this is as easy as a config change. I'll submit a pull request.
