### ISSUE TITLE
syntax highlighting is inconsistent

### ISSUE THREAD

**Issue by generalelectrix** [Krzysztof-Cieslak/vscode-elm#88]
vscode-elm seems quite inconsistent when it comes to syntax highlighting.  Here's an example screenshot (taken with the Monokai color scheme) with a few functions; declaring a function highlights the name in green, while using a function is sometimes highlighted blue and sometimes white:
![screen shot 2016-12-26 at 15 29 00](https://cloud.githubusercontent.com/assets/1912879/21487570/92522cce-cb80-11e6-91ee-f544ceb4b043.png)

The list braces are also inconsistent, where empty lists are drawn purple but lists with items are white.

This second example also seems inconsistent.  For some reason the module-qualified call to String.toInt is italicized, while non-qualified calls are not italicized:

![screen shot 2016-12-26 at 15 34 02](https://cloud.githubusercontent.com/assets/1912879/21487580/fd61f7ba-cb80-11e6-925b-481a5ce32902.png)

I also find this convention confusing; discriminated union types are purple in the declaration and when matched against, but are blue when used as a constructor.  I guess the latter is consistent with function calls, but the use of two different colors for what amount to the same identifier is a bit jarring.  This is shown in the previous screenshot.

Are there some limitations behind the scenes that prevent introspecting which values are value-like (no more arguments may be curried on) vs. function-like?

**Comment by Krzysztof-Cieslak** [comment]
The main problem is that VSCode API for syntax highlighting is purely  RegEx based so even if we would have any way for doing semantic highlighting (and I don't even know if it's possible in Elm) we wouldn't be able to plug it into the editor. I have same problems with F# plugin ;)

**Comment by StefanHub** [comment]
With 0.14.1 the syntax highlighting is currently very "pale":
![image](https://user-images.githubusercontent.com/5167310/27423042-964946a0-5730-11e7-8fb9-8615d15e145d.png)

Any idea?

However, I found this blog https://code.visualstudio.com/blogs/2017/02/08/syntax-highlighting-optimizations which mentions "manual tokenizer" that probably do not restrict to the limitations of the textMate tokenizer. But, it only mentions them.
