### ISSUE TITLE
Ability to run elm reactor in a subdirectory

### ISSUE THREAD

**Issue by radix** [Krzysztof-Cieslak/vscode-elm#90]
I have a big repo with several components of a client/server application, and my Elm project is in a subdirectory in this repo. If I start the elm reactor in vscode, it starts it at the root of my project, so it can't find my elm-package.json (and instead creates a new one and automatically downloads a bunch of dependencies that I need to clean up). It'd be nice to have some mechanism to choose a subdirectory to run elm-reactor in.

**Comment by jonsa** [comment]
I think you need to open the folder you want to run from in VS Code. I just ran the elm-reactor command on an arbitrary file opened in Code with no folder open and it started the reactor in Code installation folder giving me no access to the elm file.

If you want access to both the root project and start the reactor in the subfolder just open a new window in Code, open the folder there and start the reactor.

**Comment by radix** [comment]
@jonsa yeah, I know there are ways to work around it (I just run it in a vscode terminal), but if the feature is there in vscode it'd be nice to be able to use it.

**Comment by Krzysztof-Cieslak** [comment]
I guess we could add setting to define subdir for elm reactor.
