### ISSUE TITLE
accidentally taking screen shots!

### ISSUE THREAD

**Issue by ConnyOnny** [Krzysztof-Cieslak/vscode-elm#93]
It is ridiculous and frustrating at the same time: Whenever I hover over a closing parenthesis in my Elm code, my computer takes 5 screen shots.

It does so by calling the system program `import` (from ImageMagick). If `import` is given an argument it uses it as the file name to save to. I get three screen shots in the project directory named "Attributes", "Window" and "Task". The exact calls are
```
import Html.Attributes as Attributes
import Window
import Task
```
which is interesting because my Elm file begins with
```
import Html
import Html.Attributes as Attributes
import Window
import Task
```

To add some absurdity, the screen shots are in PostScript format, because that is apparently the default for ImageMagick if no file extension is given, but that's ImageMagick's fault.

Conclusions: Hovering over a closing parenthesis probably triggers loading of some doc. In that loading procedure there is a flaw where some parts of the Elm source code at hand are executed in a shell (I'm glad `rm -rf ~` is not a useful Elm statement)
The bug is probably not apparent if no program by the name `import` is installed in the OS path, so nobody found out before me because I am the only one in the world using VSCode to code in Elm on a machine where also ImageMagick is installed

**Comment by real-or-random** [comment]
A general comment: It's a good idea to replace all the child_process.exec() calls by child_process.execFile() calls (or child_process.spawn() calls), because they don't invoke a shell. 
If there is no shell, there is (hopefully) no shell injection.

See https://nodejs.org/api/child_process.html

**Comment by dannyob** [comment]
I think the above pull request should fix this. Because this is due to document text being output as potentially executable (and maybe damaging) shell commands, I'd encourage this to be included quickly.
