### ISSUE TITLE
Error: something like `exposing (..)` which replaced `where` in 0.17

### ISSUE THREAD

**Issue by Baudin999** [Krzysztof-Cieslak/vscode-elm#95]
(Let me prefix this by saying I'm completely new to elm, just started reading today.)

Every time I save a file, vscode-elm injects a module definition at the top of my code:

example: 

    module Main (..) where

For some reason this module definition results in the following error:

```
-- SYNTAX PROBLEM ----------------------------------------------------- test.elm

I ran into something unexpected when parsing your code!

1| module Main (..) where
               ^
I am looking for one of the following things:

    something like `exposing (..)` which replaced `where` in 0.17
    whitespace
```

As I understand it, this is because I'm running a newer version of elm compared to the injected syntax. Is there a way to disable this?

Thank you in advance

**Comment by kristianmandrup** [comment]
I'm having the same problem. Whenever I declare a module I get this error. 
Have to reboot editor for it to work!

```
- -- SYNTAX PROBLEM --------- elm-stuff/packages/elm-lang/core/3.0.0/src/Array.elm

I ran into something unexpected when parsing your code!

2|     ( Array
       ^
I am looking for one of the following things:

    something like `exposing (..)` which replaced `where` in 0.17
    whitespace
```

**Comment by kristianmandrup** [comment]
The fix is to do package install, otherwise it defaults to some old built in elm version

```
elm package install 
Some new packages are needed. Here is the upgrade plan.

  Install:
    elm-lang/core 5.1.1
    elm-lang/html 2.0.0
    elm-lang/virtual-dom 2.0.4

Do you approve of this plan? [Y/n] Y
Starting downloads...

  ● elm-lang/virtual-dom 2.0.4
  ● elm-lang/html 2.0.0
  ● elm-lang/core 5.1.1
```

**Comment by Baudin999** [comment]
Thank you for the info. I'm a bit swamped at the moment to check it out, but as soon as I have an evening I will check it out!
