### ISSUE TITLE
Add auto completions for record fields

### ISSUE THREAD

**Issue by sgronblo** [Krzysztof-Cieslak/vscode-elm#97]
```
type alias User = { name : String }

f : User -> String
f user = user.<cursor, press ctrl+space>
```

Basically the above should show name as a possible completion.

**Comment by andrewsdev** [comment]
I believe this will be resolved by the following commit: https://github.com/Krzysztof-Cieslak/vscode-elm/commit/3cb3460475b868f45cb447be491683fb700a7939

**Comment by Krzysztof-Cieslak** [comment]
👍
