### ISSUE TITLE
Tooltip for module in import showing incorrect help

### ISSUE THREAD

**Issue by doxxx** [Krzysztof-Cieslak/vscode-elm#99]
Given the following import line:

    import Html.Events exposing (onClick)

When hovering over `Html.Events`, the tooltip displays the following help text:

> { stopPropagation : Bool
>   , preventDefault : Bool 
>   }
> Options for an event listener. If stopPropagation is true, it means the event stops traveling through the DOM so it will not trigger any other event listeners. If preventDefault is true, any built-in browser behavior related to the event is prevented. For example, this is used with touch events when you want to treat them as gestures of your own, not as scrolls.

This appears to be the help text for the `Options` type alias in the `Html.Events` module. I would have expected to see the help text that appears near the beginning of that module, which starts with:

> It is often helpful to create an [Union Type][] so you can have many different kinds
of events as seen in the [TodoMVC][] example.

The same thing happens with other imports.

**Comment by Krzysztof-Cieslak** [comment]
Can't reproduce with current version of Elm plugin
